$env:GIT = "E:/dev/git/"
$env:GAMEDEV = "E:/dev/gamedev/"
$env:PERSONAL = "E:/dev/personal/"
$env:DOWNLOAD = "E:/Downloads/"
$env:TERMINAL_SETTINGS = "C:/Users/alihu/AppData/Local/Packages/Microsoft.WindowsTerminal_8wekyb3d8bbwe/LocalState/settings.json"
