$env:GIT = "D:/dev/git/"
$env:PERSONAL = "D:/dev/personal/"
$env:DOWNLOAD = "D:/Downloads/"
$env:DOWNLOAD_VIDEOS = "D:/Downloads/Video/"
$env:DOWNLOAD_PROGRAMS = "D:/Downloads/Programs/"
$env:TERMINAL_SETTINGS = "C:/Users/alihu/AppData/Local/Packages/Microsoft.WindowsTerminal_8wekyb3d8bbwe/LocalState/settings.json"
